{% set version = "5.5.2.0-17.12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lpsolveapi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lpSolveAPI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lpSolveAPI/lpSolveAPI_{{ version }}.tar.gz
  sha256: 4f00a9d27055ddf3e2a4b0a529b720861b9f916f2ceb1fe0b71e4c52da5b70ef

build:
  number: 1
  rpaths:
    - lib/R/library/lpSolveAPI/libs
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - libblas
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('lpSolveAPI')"           # [not win]
    - "\"%R%\" -e \"library('lpSolveAPI')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lpSolveAPI
  license: LGPL-2.1-only
  summary: The lpSolveAPI package provides an R interface to 'lp_solve', a Mixed Integer Linear Programming (MILP) solver with support for pure linear, (mixed) integer/binary, semi-continuous and special ordered sets (SOS) models.
  license_family: LGPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
