appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: 1sj91YNgDHMwiMQovQSckjI3qv5PIeY7P8Fm6kglbx/7G/Gc0epT2GFgKcD1PPssE/7wc5z1zhXSD0XFryR8TtVcVbR89cFjLsNNRZd4IrWNWT6Fe7+2/2UJbwhBvxvUheDwarq1/Ity0P9MS01FyAGMpgYGSVwWlsYxBj6lSCt6+uhLRLgr8v7DUbCN0hyY3Jg9hXOY1QAEuW14Ejp+ZdrVnFej2doGgzRnxm3acx+QnPzQFR+GTPQMUh/muCRDGiF6A1sKT50vdNhjHXwBMfxGXzvu+9Fn3/Dvp1f0+YguNlRSFI5rY9ldA9aP64rlz+no22aoXzIXGXJbEVlG8QzC1KbhOgJMf53ZE/owkeT4r1WbEYTF+PbmYpLg7jL10eXwHtXNMP7zT/xyRFIQMCq1Zv9euGRPF3A+wonV7rcXyOVWnwqbMxa+7A1jHS2aW5Xgu/vPgHypLoEAO4lxKmOEQUvfFoBtosXav+uBfa9/9wsVy3mpHhoBAm8zU2mgXKESoZlhElL+imUr3NJ7NIAV65R+zUzSPasY3QVfKcx6JbS8542r8pSiWYH2b5OEuzriej6XY2GTuqtxCr6gyzNhKtfF31kGDCGaGHU0mldOurgTsswKcpJyRcvCdCOpXRXhSjPr5cV8lLy77WcHPxjq+ClKCEoX5UUvDVKPLFM=
conda_forge_output_validation: true
